import { useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowRight, BookOpen, Check, ChevronLeft, ChevronRight, LoaderCircle, ShieldCheck, X } from 'lucide-react'
import { api, type AvailabilitySlot, type BookingGroup, type Court, type UserProfile } from './api'
import type { User } from 'firebase/auth'
import heroImage from './assets/luxury-court-hero.png'
import SiteHeader from './SiteHeader'
import { useLanguage } from './LanguageContext'

function localDate(offset = 1) { const d = new Date(); d.setDate(d.getDate() + offset); return dateKey(d) }
function dateKey(d: Date) { return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` }
function iso(date: string, time: string) { return new Date(`${date}T${time}:00`).toISOString() }
function clock(value: string) { return new Date(value).toLocaleTimeString('en-ID', { hour: '2-digit', minute: '2-digit', hour12: false }) }

function LocationIcon() { return <svg className="google-maps-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 10c0 5.5-8 12-8 12S4 15.5 4 10a8 8 0 1 1 16 0Z" fill="none" stroke="currentColor" strokeWidth="1.6" /><circle cx="12" cy="10" r="2.6" fill="none" stroke="currentColor" strokeWidth="1.6" /></svg> }

export default function BookingExperience() {
  const { language } = useLanguage()
  const id = language === 'id'
  const displayDate = useMemo(() => new Intl.DateTimeFormat(id ? 'id-ID' : 'en-ID', { weekday: 'short', day: 'numeric', month: 'long' }), [id])
  const [date, setDate] = useState(localDate()), [month, setMonth] = useState(() => { const d = new Date(); d.setDate(1); return d })
  const [slots, setSlots] = useState<AvailabilitySlot[]>([]), [selectedSlot, setSelectedSlot] = useState<AvailabilitySlot | null>(null)
  const [courts, setCourts] = useState<Court[]>([]), [selectedCourtIds, setSelectedCourtIds] = useState<string[]>([]), [step, setStep] = useState<'schedule' | 'courts'>('schedule')
  const [duration, setDuration] = useState(60), [courtCount, setCourtCount] = useState(1)
  const [searching, setSearching] = useState(false), [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState(''), [booking, setBooking] = useState<BookingGroup | null>(null), [reservationOpen, setReservationOpen] = useState(() => new URLSearchParams(window.location.search).get('reserve') === '1')
  const [currentUser, setCurrentUser] = useState<User | null>(null), [profile, setProfile] = useState<UserProfile | null>(null)
  const dayRange = useMemo(() => ({ startsAt: iso(date, '07:00'), endsAt: iso(date, '23:00') }), [date])
  const calendarDays = useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1), start = new Date(first); start.setDate(1 - first.getDay()); return Array.from({ length: 42 }, (_, i) => { const d = new Date(start); d.setDate(start.getDate() + i); return d }) }, [month])

  useEffect(() => { if (!reservationOpen) return; setSearching(true); setStep('schedule'); setSelectedSlot(null); setSelectedCourtIds([]); setError(''); api.getAvailability(dayRange.startsAt, dayRange.endsAt, duration).then(setSlots).catch((e: Error) => setError(e.message)).finally(() => setSearching(false)) }, [reservationOpen, date, duration, dayRange.startsAt, dayRange.endsAt])
  const handleSession = useCallback((user: User | null, value: UserProfile | null) => { setCurrentUser(user); setProfile(value) }, [])

  async function chooseSlot(slot: AvailabilitySlot) { setSelectedSlot(slot); setSelectedCourtIds([]); setSearching(true); setError(''); try { setCourts(await api.getCourts(slot.startsAt, slot.endsAt)); setStep('courts') } catch (reason) { setError(reason instanceof Error ? reason.message : id ? 'Lapangan tidak dapat dimuat.' : 'Could not load courts.') } finally { setSearching(false) } }
  function toggleCourt(court: Court) { if (!court.isAvailable) return; setSelectedCourtIds(current => current.includes(court.id) ? current.filter(id => id !== court.id) : current.length < courtCount ? [...current, court.id] : current) }
  async function submitBooking(e: React.FormEvent) { e.preventDefault(); if (!selectedSlot || selectedCourtIds.length !== courtCount) return; if (!currentUser || !profile) { setError(id ? 'Silakan masuk atau daftar sebelum memesan.' : 'Please login or sign up before booking.'); return } setSubmitting(true); setError(''); try { setBooking(await api.createBookingGroup({ startsAt: selectedSlot.startsAt, endsAt: selectedSlot.endsAt, courtIds: selectedCourtIds })) } catch (reason) { setError(reason instanceof Error ? reason.message : id ? 'Pemesanan tidak dapat dibuat.' : 'Could not create booking.'); try { setCourts(await api.getCourts(selectedSlot.startsAt, selectedSlot.endsAt)); setSelectedCourtIds([]) } catch { /* Keep the booking error visible. */ } } finally { setSubmitting(false) } }

  return <div className="app-shell">
    <SiteHeader active="home" onSession={handleSession} onReserve={() => setReservationOpen(true)} />
    <main id="top"><section className="hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(4,13,10,.97) 0%, rgba(4,13,10,.85) 37%, rgba(4,13,10,.15) 72%), url(${heroImage})` }}><div className="hero-copy"><p className="overline">{id ? 'Lapangan Bulu Tangkis' : 'Badminton Court'}</p><h1>{id ? <>Tempat setiap<br />reli terasa <em>istimewa.</em></> : <>Where every<br />rally feels <em>rare.</em></>}</h1><p className="hero-lead">{id ? <>Lapangan istimewa. Reservasi mudah.<br />Bulu tangkis, lebih berkelas.</> : <>Exceptional courts. Effortless reservations.<br />Badminton, elevated.</>}</p><div className="hero-actions"><button className="primary-button animated-reserve" onClick={() => setReservationOpen(true)}><BookOpen className="button-leading-icon" size={17} /><span className="reserve-label">{id ? 'Pesan lapangan Anda' : 'Reserve your court'}</span><ArrowRight className="reveal-arrow" size={17} /></button><a className="maps-button" href="https://maps.google.com" target="_blank" rel="noreferrer"><LocationIcon /><span>{id ? 'Lihat lokasi kami' : 'View our location'}</span><ArrowRight className="maps-reveal-arrow" size={17} /></a></div></div><div className="hero-aside"><span>{id ? 'SEJAK' : 'EST.'}</span><strong>2026</strong><i /></div></section>

      {reservationOpen && <div className="reservation-backdrop" role="dialog" aria-modal="true" aria-label={id ? 'Pesan lapangan' : 'Reserve a court'}><section className="booking-section reservation-dialog"><button className="reservation-close" aria-label={id ? 'Tutup reservasi' : 'Close reservation'} onClick={() => setReservationOpen(false)}><X size={20} /></button>
        {step === 'schedule' ? <>
          <div className="scheduler-heading"><p className="overline gold">{id ? 'Reservasi lapangan · Langkah 1 dari 2' : 'Court reservations · Step 1 of 2'}</p><h2>{id ? 'Pilih sesi Anda.' : 'Choose your session.'}</h2></div>
          <div className="schedule-modal">
            <div className="calendar-pane"><div className="calendar-top"><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} aria-label={id ? 'Bulan sebelumnya' : 'Previous month'}><ChevronLeft /></button><strong>{month.toLocaleDateString(id ? 'id-ID' : 'en-ID', { month: 'long', year: 'numeric' })}</strong><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} aria-label={id ? 'Bulan berikutnya' : 'Next month'}><ChevronRight /></button></div><div className="calendar-weekdays">{(id ? ['MIN','SEN','SEL','RAB','KAM','JUM','SAB'] : ['SUN','MON','TUE','WED','THU','FRI','SAT']).map(d => <span key={d}>{d}</span>)}</div><div className="calendar-grid">{calendarDays.map(day => { const key = dateKey(day), outside = day.getMonth() !== month.getMonth(), past = key < localDate(0); return <button key={key} disabled={past} className={`${outside ? 'outside' : ''} ${key === date ? 'active' : ''}`} onClick={() => setDate(key)}><span>{day.getDate()}</span></button> })}</div></div>
            <div className="sessions-pane"><div className="sessions-top"><div><small>{id ? 'SESI TERSEDIA' : 'AVAILABLE SESSIONS'}</small><h3>{displayDate.format(new Date(`${date}T12:00:00`))}</h3></div></div><div className="booking-options"><label><span>{id ? 'DURASI' : 'DURATION'}</span><select value={duration} onChange={e => setDuration(Number(e.target.value))}>{[1,2,3,4].map(hours => <option key={hours} value={hours * 60}>{hours} {id ? 'jam' : hours === 1 ? 'hour' : 'hours'}</option>)}</select></label><label><span>{id ? 'LAPANGAN' : 'COURTS'}</span><select value={courtCount} onChange={e => { setCourtCount(Number(e.target.value)); setSelectedSlot(null) }}>{[1,2,3].map(count => <option key={count} value={count}>{count} {id ? 'lapangan' : count === 1 ? 'court' : 'courts'}</option>)}</select></label></div><div className="slot-legend"><span><i className="available" />{id ? 'Tersedia' : 'Available'}</span><span><i className="held" />{id ? 'Terbatas / ditahan' : 'Limited / on hold'}</span><span><i className="booked" />{id ? 'Dipesan' : 'Booked'}</span></div>{error && <div className="alert"><X size={17} />{error}</div>}{searching ? <div className="sessions-loading"><LoaderCircle className="spin" /> {id ? 'Memeriksa lapangan…' : 'Checking the courts…'}</div> : <div className="modal-time-grid">{slots.map(slot => { const past = new Date(slot.startsAt) <= new Date(), noneAvailable = slot.availableCourts === 0, limited = !past && slot.availableCourts > 0 && slot.availableCourts < courtCount, unavailable = past || noneAvailable || limited; return <button key={slot.startsAt} disabled={unavailable} className={`${limited || (!past && noneAvailable && slot.heldCourts > 0) ? 'held' : unavailable ? 'booked' : 'available'}`} onClick={() => chooseSlot(slot)}><strong>{clock(slot.startsAt)}–{clock(slot.endsAt)}</strong><small>{past ? (id ? 'Sudah lewat' : 'Past') : limited ? `${slot.availableCourts} ${id ? 'lapangan tersisa' : 'courts remaining'}` : noneAvailable && slot.heldCourts > 0 ? (id ? 'Ditahan' : 'On hold') : noneAvailable ? (id ? 'Dipesan' : 'Booked') : `${slot.availableCourts} ${id ? 'lapangan tersisa' : 'courts remaining'}`}</small></button> })}</div>}</div>
          </div>
        </> : selectedSlot && <>
          <div className="scheduler-heading court-step-heading"><button className="step-back" onClick={() => { setStep('schedule'); setSelectedCourtIds([]); setError('') }}><ChevronLeft size={17} /> {id ? 'Ubah waktu' : 'Change time'}</button><p className="overline gold">{id ? 'Reservasi lapangan · Langkah 2 dari 2' : 'Court reservations · Step 2 of 2'}</p><h2>{id ? `Pilih ${courtCount} lapangan Anda.` : `Choose your ${courtCount === 1 ? 'court' : 'courts'}.`}</h2><p>{displayDate.format(new Date(selectedSlot.startsAt))} · {clock(selectedSlot.startsAt)}–{clock(selectedSlot.endsAt)} · {id ? `Pilih ${courtCount}.` : `Select ${courtCount}.`}</p></div>
          <div className="court-picker-legend slot-legend"><span><i className="available" />{id ? 'Tersedia' : 'Available'}</span><span><i className="held" />{id ? 'Ditahan' : 'On hold'}</span><span><i className="booked" />{id ? 'Dipesan' : 'Booked'}</span></div>
          {error && <div className="alert"><X size={17} />{error}</div>}
          {searching ? <div className="sessions-loading"><LoaderCircle className="spin" /> {id ? 'Memuat lapangan…' : 'Loading courts…'}</div> : <div className="court-picker-grid">{courts.map((court, index) => { const selected = selectedCourtIds.includes(court.id); return <button key={court.id} disabled={!court.isAvailable} className={`court-pick ${court.status} ${selected ? 'selected' : ''}`} onClick={() => toggleCourt(court)}><span className="court-pick-number">0{index + 1}</span><span className="court-pick-lines"><i /></span><strong>{court.name}</strong><small>{selected ? (id ? 'Dipilih' : 'Selected') : court.status === 'available' ? (id ? 'Tersedia' : 'Available') : court.status === 'held' ? (id ? 'Ditahan' : 'On hold') : (id ? 'Dipesan' : 'Booked')}</small>{selected && <Check size={20} />}</button> })}</div>}
          <form className="court-confirm" onSubmit={submitBooking}><div><strong>{id ? `${selectedCourtIds.length} dari ${courtCount} dipilih` : `${selectedCourtIds.length} of ${courtCount} selected`}</strong><p>{profile ? (id ? `Memesan sebagai ${profile.username} (${profile.phoneNumber})` : `Booking as ${profile.username} (${profile.phoneNumber})`) : (id ? 'Masuk atau buat akun sebelum mengonfirmasi.' : 'Login or create an account before confirming.')}</p></div><button className="primary-button" disabled={submitting || !profile || selectedCourtIds.length !== courtCount}>{submitting ? <LoaderCircle className="spin" size={18} /> : <ShieldCheck size={17} />} {id ? 'Konfirmasi lapangan' : 'Confirm courts'} <ArrowRight size={17} /></button></form>
        </>}
      </section></div>}
    </main>
    {booking && <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="success-modal"><div className="success-icon"><Check size={26} /></div><p className="overline gold">{id ? 'Reservasi ditahan' : 'Reservation held'}</p><h2>{id ? 'Sampai jumpa di lapangan.' : 'See you on court.'}</h2><p><strong>{booking.courtCount} {id ? 'lapangan' : booking.courtCount === 1 ? 'court is' : 'courts are'}</strong> {id ? 'ditahan selama 20 menit hingga pembayaran selesai.' : 'held for 20 minutes while payment is completed.'}</p><div className="booking-code"><small>{id ? 'REFERENSI PEMESANAN' : `BOOKING REFERENCE${booking.courtCount > 1 ? 'S' : ''}`}</small><strong>{booking.bookings.map(b => b.bookingCode).join(' · ')}</strong></div><button className="primary-button" onClick={() => { setBooking(null); setReservationOpen(false) }}>{id ? 'Selesai' : 'Done'} <ArrowRight size={17} /></button></div></div>}
  </div>
}
