import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, CalendarDays, Check, ChevronDown, Clock3, LoaderCircle, MapPin, ShieldCheck, X } from 'lucide-react'
import { api, type AvailabilitySlot, type Booking, type Venue } from './api'

function localDate(offset = 1) { const d = new Date(); d.setDate(d.getDate() + offset); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` }
const iso = (date: string, time: string) => new Date(`${date}T${time}:00`).toISOString()
const clock = (value: string) => new Date(value).toLocaleTimeString('en-ID', { hour: '2-digit', minute: '2-digit', hour12: false })

export default function BookingApp() {
  const [venues, setVenues] = useState<Venue[]>([]), [venueId, setVenueId] = useState('')
  const [date, setDate] = useState(localDate()), [duration, setDuration] = useState(60)
  const [slots, setSlots] = useState<AvailabilitySlot[]>([]), [selected, setSelected] = useState<AvailabilitySlot | null>(null)
  const [loading, setLoading] = useState(true), [searching, setSearching] = useState(false), [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState(''), [booking, setBooking] = useState<Booking | null>(null)
  const [now, setNow] = useState(Date.now())
  const [form, setForm] = useState({ customerName: '', customerEmail: '', customerPhone: '' })
  const day = useMemo(() => ({ startsAt: iso(date, '06:00'), endsAt: iso(date, '23:00') }), [date])
  useEffect(() => { api.getVenues().then(v => { setVenues(v); setVenueId(v[0]?.id ?? '') }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }, [])
  useEffect(() => { if (!booking) return; setNow(Date.now()); const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer) }, [booking])
  async function showTimes() { setSearching(true); setSelected(null); setError(''); try { setSlots(await api.getAvailability(venueId, day.startsAt, day.endsAt, duration)) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load times.') } finally { setSearching(false) } }
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!selected) return; setSubmitting(true); setError(''); try { setBooking(await api.createBooking({ venueId, ...form, startsAt: selected.startsAt, endsAt: selected.endsAt })) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not create booking.'); await showTimes() } finally { setSubmitting(false) } }

  return <div className="app-shell"><header className="site-header"><a className="brand" href="#top"><span className="brand-mark"><span /></span>JSPORT</a><nav><a href="#book">Book</a><a href="#why">Why JSport</a></nav><a className="header-cta" href="#book">Book now <ArrowRight size={16}/></a></header><main id="top">
    <section className="hero-section"><div className="hero-copy"><div className="eyebrow">THREE COURTS · ONE EASY BOOKING</div><h1>Play more.<br/><em>Wait less.</em></h1><p>Choose your time and we will automatically assign the best available court.</p><a className="primary-button" href="#book">Choose a time <ArrowRight size={18}/></a></div><div className="court-art"><div className="court-lines"><span className="net"/><span className="center-line"/></div><div className="shuttle"><i/><b/></div><div className="court-card"><Clock3 size={19}/><span><small>LIVE AVAILABILITY</small><strong>3 courts</strong></span></div></div></section>
    <section className="booking-section" id="book"><div className="section-heading"><div><span className="step-label">01 — BOOK</span><h2>When do you want to play?</h2></div><p>Choose a session like a movie time. Past and unavailable sessions are disabled.</p></div>
      <div className="search-panel compact-search"><label><span><MapPin size={17}/> Venue</span><div className="select-wrap"><select value={venueId} onChange={e => setVenueId(e.target.value)} disabled={loading}>{loading ? <option>Loading…</option> : venues.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select><ChevronDown size={17}/></div></label><label><span><CalendarDays size={17}/> Date</span><input type="date" min={localDate(0)} value={date} onChange={e => setDate(e.target.value)}/></label><label><span><Clock3 size={17}/> Duration</span><div className="select-wrap"><select value={duration} onChange={e => setDuration(Number(e.target.value))}><option value="60">1 hour</option><option value="90">1.5 hours</option><option value="120">2 hours</option><option value="180">3 hours</option></select><ChevronDown size={17}/></div></label><button className="search-button" onClick={showTimes} disabled={searching || !venueId}>{searching ? <LoaderCircle className="spin" size={19}/> : <ArrowRight size={19}/>} Show times</button></div>
      {error && <div className="alert"><X size={18}/>{error}</div>}
      {slots.length > 0 && <div className="results-area"><div className="results-title"><h3>Choose a start time</h3><span>Automatic court assignment</span></div><div className="slot-legend"><span><i className="green"/>Available</span><span><i className="yellow"/>On hold</span><span><i className="gray"/>Booked or past</span></div><div className="time-grid">{slots.map(s => { const past = new Date(s.startsAt) <= new Date(), unavailable = past || s.availableCourts === 0, held = !past && unavailable && s.heldCourts > 0; return <button key={s.startsAt} disabled={unavailable} className={`${selected?.startsAt === s.startsAt ? 'selected' : ''} ${held ? 'held' : ''}`} onClick={() => setSelected(s)}><strong>{clock(s.startsAt)}</strong><small>{past ? 'Past' : held ? 'On hold' : unavailable ? 'Full' : `${s.availableCourts} left`}</small></button> })}</div></div>}
      {selected && <div className="checkout-panel"><div className="checkout-summary"><span className="step-label">02 — DETAILS</span><h2>Almost game time.</h2><p>Confirm to hold an automatically assigned court for 20 minutes while you pay.</p><div className="summary-card"><div><small>COURT</small><strong>Automatically assigned</strong></div><div><small>DATE & TIME</small><strong>{new Date(selected.startsAt).toLocaleDateString('en-ID',{day:'numeric',month:'short'})} · {clock(selected.startsAt)}</strong></div><div><small>DURATION</small><strong>{duration} minutes</strong></div></div></div><form onSubmit={submit}><label>Full name<input required maxLength={150} value={form.customerName} onChange={e => setForm({...form,customerName:e.target.value})}/></label><label>Email<input required type="email" maxLength={254} value={form.customerEmail} onChange={e => setForm({...form,customerEmail:e.target.value})}/></label><label>WhatsApp number<input required type="tel" maxLength={30} value={form.customerPhone} onChange={e => setForm({...form,customerPhone:e.target.value})}/></label><button className="primary-button submit-button" disabled={submitting}>{submitting ? <LoaderCircle className="spin" size={19}/> : <ShieldCheck size={19}/>} Confirm & continue to payment</button></form></div>}
    </section><section className="why-section" id="why"><div><span className="step-label">WHY JSPORT</span><h2>Less admin.<br/>More badminton.</h2></div><div className="benefits"><article><strong>01</strong><h3>Live time slots</h3><p>Available, held, and booked states at a glance.</p></article><article><strong>02</strong><h3>Automatic assignment</h3><p>You pick when. We handle where.</p></article><article><strong>03</strong><h3>20-minute hold</h3><p>Your assigned court stays safe while you pay.</p></article></div></section>
  </main><footer><div className="brand"><span className="brand-mark"><span/></span>JSPORT</div><p>Good games start with an easy booking.</p><span>© 2026 JSport</span></footer>{booking && <div className="modal-backdrop"><div className="success-modal"><div className="success-icon"><Check size={30}/></div><span className="step-label">COURT ON HOLD</span><h2>Complete your payment.</h2><p><strong>{booking.courtName}</strong> is reserved for 20 minutes.</p><div className="hold-timer"><Clock3 size={18}/> {Math.max(0, Math.floor((new Date(booking.holdExpiresAt).getTime() - now) / 60000)).toString().padStart(2,'0')}:{Math.max(0, Math.floor((new Date(booking.holdExpiresAt).getTime() - now) / 1000) % 60).toString().padStart(2,'0')} remaining</div><div className="booking-code"><small>BOOKING CODE</small><strong>{booking.bookingCode}</strong></div><button className="primary-button" onClick={() => setBooking(null)}>Done</button></div></div>}</div>
}
