import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, BookOpen, Check, ChevronLeft, ChevronRight, LoaderCircle, ShieldCheck, X } from 'lucide-react'
import { api, type AvailabilitySlot, type BookingGroup, type Venue } from './api'
import heroImage from './assets/luxury-court-hero.png'

const displayDate = new Intl.DateTimeFormat('en-ID', { weekday: 'short', day: 'numeric', month: 'long' })
function localDate(offset = 1) { const d = new Date(); d.setDate(d.getDate() + offset); return dateKey(d) }
function dateKey(d: Date) { return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` }
function iso(date: string, time: string) { return new Date(`${date}T${time}:00`).toISOString() }
function clock(value: string) { return new Date(value).toLocaleTimeString('en-ID', { hour: '2-digit', minute: '2-digit', hour12: false }) }

function Brand() { return <span className="brand"><span className="brand-shuttle"><i /><i /><i /></span><span>JSPORT<small>RACQUET CLUB</small></span></span> }
function LocationIcon() { return <svg className="google-maps-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 10c0 5.5-8 12-8 12S4 15.5 4 10a8 8 0 1 1 16 0Z" fill="none" stroke="currentColor" strokeWidth="1.6" /><circle cx="12" cy="10" r="2.6" fill="none" stroke="currentColor" strokeWidth="1.6" /></svg> }

export default function BookingExperience() {
  const [venues, setVenues] = useState<Venue[]>([]), [venueId, setVenueId] = useState('')
  const [date, setDate] = useState(localDate()), [month, setMonth] = useState(() => { const d = new Date(); d.setDate(1); return d })
  const [slots, setSlots] = useState<AvailabilitySlot[]>([]), [selectedSlot, setSelectedSlot] = useState<AvailabilitySlot | null>(null)
  const [duration, setDuration] = useState(60), [courtCount, setCourtCount] = useState(1)
  const [loading, setLoading] = useState(true), [searching, setSearching] = useState(false), [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState(''), [booking, setBooking] = useState<BookingGroup | null>(null), [reservationOpen, setReservationOpen] = useState(false)
  const [form, setForm] = useState({ customerName: '', customerEmail: '', customerPhone: '' })
  const venue = venues.find(v => v.id === venueId)
  const dayRange = useMemo(() => ({ startsAt: iso(date, '07:00'), endsAt: iso(date, '23:00') }), [date])
  const calendarDays = useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1), start = new Date(first); start.setDate(1 - first.getDay()); return Array.from({ length: 42 }, (_, i) => { const d = new Date(start); d.setDate(start.getDate() + i); return d }) }, [month])

  useEffect(() => { api.getVenues().then(v => { setVenues(v); setVenueId(v[0]?.id ?? '') }).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }, [])
  useEffect(() => { if (!reservationOpen || !venueId) return; setSearching(true); setSelectedSlot(null); setError(''); api.getAvailability(venueId, dayRange.startsAt, dayRange.endsAt, duration).then(setSlots).catch((e: Error) => setError(e.message)).finally(() => setSearching(false)) }, [reservationOpen, venueId, date, duration, dayRange.startsAt, dayRange.endsAt])

  async function submitBooking(e: React.FormEvent) { e.preventDefault(); if (!selectedSlot) return; setSubmitting(true); setError(''); try { setBooking(await api.createBookingGroup({ venueId, ...form, startsAt: selectedSlot.startsAt, endsAt: selectedSlot.endsAt, courtCount })) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not create booking.') } finally { setSubmitting(false) } }

  return <div className="app-shell">
    <header className="site-header"><a href="/" aria-label="JSport home"><Brand /></a><nav className="header-tabs" aria-label="Primary navigation"><a className="active" href="/">Home</a><a href="/events">Events</a></nav><button className="header-cta" onClick={() => setReservationOpen(true)}>Reserve a court <ArrowRight size={16} /></button></header>
    <main id="top"><section className="hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(4,13,10,.97) 0%, rgba(4,13,10,.85) 37%, rgba(4,13,10,.15) 72%), url(${heroImage})` }}><div className="hero-copy"><p className="overline"><span /> Jakarta's private court experience</p><h1>Where every<br />rally feels <em>rare.</em></h1><p className="hero-lead">Exceptional courts. Effortless reservations.<br />Badminton, elevated.</p><div className="hero-actions"><button className="primary-button animated-reserve" onClick={() => setReservationOpen(true)}><BookOpen className="button-leading-icon" size={17} /><span className="reserve-label">Reserve your court</span><ArrowRight className="reveal-arrow" size={17} /></button><a className="maps-button" href="https://maps.google.com" target="_blank" rel="noreferrer"><LocationIcon /><span>View our location</span><ArrowRight className="maps-reveal-arrow" size={17} /></a></div></div><div className="hero-aside"><span>EST.</span><strong>2026</strong><i /></div></section>

      {reservationOpen && <div className="reservation-backdrop" role="dialog" aria-modal="true" aria-label="Reserve a court"><section className="booking-section reservation-dialog"><button className="reservation-close" aria-label="Close reservation" onClick={() => setReservationOpen(false)}><X size={20} /></button>
        <div className="scheduler-heading"><p className="overline gold">Court reservations</p><h2>Choose your session.</h2><p>Every reservation is one hour. Your court is assigned automatically.</p></div>
        <div className="schedule-modal">
          <div className="calendar-pane"><div className="calendar-top"><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} aria-label="Previous month"><ChevronLeft /></button><strong>{month.toLocaleDateString('en-ID', { month: 'long', year: 'numeric' })}</strong><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} aria-label="Next month"><ChevronRight /></button></div><div className="calendar-weekdays">{['SUN','MON','TUE','WED','THU','FRI','SAT'].map(d => <span key={d}>{d}</span>)}</div><div className="calendar-grid">{calendarDays.map(day => { const key = dateKey(day), outside = day.getMonth() !== month.getMonth(), past = key < localDate(0); return <button key={key} disabled={past} className={`${outside ? 'outside' : ''} ${key === date ? 'active' : ''}`} onClick={() => setDate(key)}><span>{day.getDate()}</span></button> })}</div><div className="calendar-club"><small>PLAYING AT</small><strong>{loading ? 'Loading club…' : venue?.name}</strong></div></div>
          <div className="sessions-pane"><div className="sessions-top"><div><small>AVAILABLE SESSIONS</small><h3>{displayDate.format(new Date(`${date}T12:00:00`))}</h3></div></div><div className="booking-options"><label><span>DURATION</span><select value={duration} onChange={e => setDuration(Number(e.target.value))}><option value={60}>1 hour</option><option value={120}>2 hours</option><option value={180}>3 hours</option><option value={240}>4 hours</option></select></label><label><span>COURTS</span><select value={courtCount} onChange={e => { setCourtCount(Number(e.target.value)); setSelectedSlot(null) }}><option value={1}>1 court</option><option value={2}>2 courts</option><option value={3}>3 courts</option></select></label></div><div className="slot-legend"><span><i className="available" />Available</span><span><i className="held" />On hold</span><span><i className="booked" />Booked</span></div>{error && <div className="alert"><X size={17} />{error}</div>}{searching ? <div className="sessions-loading"><LoaderCircle className="spin" /> Checking the courts…</div> : <div className="modal-time-grid">{slots.map(slot => { const past = new Date(slot.startsAt) <= new Date(), unavailable = past || slot.availableCourts < courtCount, held = !past && unavailable && slot.heldCourts > 0; return <button key={slot.startsAt} disabled={unavailable} className={`${selectedSlot?.startsAt === slot.startsAt ? 'selected' : ''} ${held ? 'held' : unavailable ? 'booked' : 'available'}`} onClick={() => setSelectedSlot(slot)}><strong>{clock(slot.startsAt)}–{clock(slot.endsAt)}</strong><small>{past ? 'Past' : held ? 'On hold' : unavailable ? 'Not enough courts' : `${slot.availableCourts} courts left`}</small></button> })}</div>}</div>
        </div>
        {selectedSlot && <div className="slot-checkout"><div className="slot-summary"><p className="overline gold">Selected session</p><h3>{clock(selectedSlot.startsAt)}–{clock(selectedSlot.endsAt)}</h3><p>{displayDate.format(new Date(selectedSlot.startsAt))} · {courtCount} {courtCount === 1 ? 'court' : 'courts'} · Court assignment automatic</p></div><form onSubmit={submitBooking}><label>Full name<input required maxLength={150} placeholder="Your full name" value={form.customerName} onChange={e => setForm({ ...form, customerName: e.target.value })} /></label><label>Email<input required type="email" maxLength={254} placeholder="you@example.com" value={form.customerEmail} onChange={e => setForm({ ...form, customerEmail: e.target.value })} /></label><label>WhatsApp<input required type="tel" maxLength={30} placeholder="+62 812 3456 7890" value={form.customerPhone} onChange={e => setForm({ ...form, customerPhone: e.target.value })} /></label><button className="primary-button" disabled={submitting}>{submitting ? <LoaderCircle className="spin" size={18} /> : <ShieldCheck size={17} />} Hold this session <ArrowRight size={17} /></button></form></div>}
      </section></div>}
    </main>
    <footer id="contact"><Brand /><p>Private courts. Exceptional play.</p><div><button className="footer-reserve" onClick={() => setReservationOpen(true)}>Reservations</button><span>© 2026 JSport</span></div></footer>
    {booking && <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="success-modal"><div className="success-icon"><Check size={26} /></div><p className="overline gold">Reservation held</p><h2>See you on court.</h2><p><strong>{booking.courtCount} {booking.courtCount === 1 ? 'court is' : 'courts are'}</strong> held for 20 minutes while payment is completed.</p><div className="booking-code"><small>BOOKING REFERENCE{booking.courtCount > 1 ? 'S' : ''}</small><strong>{booking.bookings.map(b => b.bookingCode).join(' · ')}</strong></div><button className="primary-button" onClick={() => { setBooking(null); setReservationOpen(false) }}>Done <ArrowRight size={17} /></button></div></div>}
  </div>
}
