import { Ban, Briefcase, Clock3, Footprints, GlassWater, HandHeart, ShieldCheck, Users } from 'lucide-react'
import SiteHeader from './SiteHeader'
import { useLanguage } from './LanguageContext'

const rules = [
  { tone: 'required', icon: Footprints, sign: { en: 'REQUIRED', id: 'WAJIB' }, title: { en: 'Court shoes on', id: 'Gunakan sepatu lapangan' }, detail: { en: 'Clean indoor badminton shoes with non-marking soles are mandatory. Leave outdoor and hard-soled shoes off the playing surface.', id: 'Wajib memakai sepatu bulu tangkis dalam ruangan yang bersih dan tidak meninggalkan bekas. Jangan gunakan sepatu luar ruangan di area bermain.' } },
  { tone: 'prohibited', icon: Ban, sign: { en: 'NO FOOD', id: 'DILARANG MAKAN' }, title: { en: 'Keep food off court', id: 'Jangan membawa makanan' }, detail: { en: 'Food, chewing gum, and open drinks belong in the café or lounge—not inside the court area.', id: 'Makanan, permen karet, dan minuman terbuka hanya boleh dinikmati di kafe atau lounge, bukan di area lapangan.' } },
  { tone: 'allowed', icon: GlassWater, sign: { en: 'WATER OK', id: 'AIR DIPERBOLEHKAN' }, title: { en: 'Hydrate safely', id: 'Minum dengan aman' }, detail: { en: 'Closed water bottles are welcome beside the court. Keep them upright and outside the boundary lines.', id: 'Botol air tertutup boleh diletakkan di sisi lapangan. Pastikan tetap tegak dan berada di luar garis lapangan.' } },
  { tone: 'timing', icon: Clock3, sign: { en: 'ON TIME', id: 'TEPAT WAKTU' }, title: { en: 'Respect every session', id: 'Hormati setiap sesi' }, detail: { en: 'Enter when your booking begins and finish promptly so the next group receives its full court time.', id: 'Masuk saat jadwal Anda dimulai dan selesaikan tepat waktu agar kelompok berikutnya mendapat waktu bermain penuh.' } },
  { tone: 'safety', icon: Briefcase, sign: { en: 'KEEP CLEAR', id: 'JAGA TETAP AMAN' }, title: { en: 'Bags stay courtside', id: 'Simpan tas di sisi lapangan' }, detail: { en: 'Store rackets, bags, and loose belongings away from boundaries and walkways to prevent trips.', id: 'Simpan raket, tas, dan barang lainnya jauh dari garis lapangan dan jalur berjalan untuk mencegah tersandung.' } },
  { tone: 'respect', icon: HandHeart, sign: { en: 'PLAY KIND', id: 'BERMAIN DENGAN BAIK' }, title: { en: 'Good games, good manners', id: 'Permainan baik, sikap baik' }, detail: { en: 'Use respectful language, manage noise, and be considerate of players on neighbouring courts.', id: 'Gunakan bahasa yang sopan, jaga tingkat kebisingan, dan hormati pemain di lapangan sebelah.' } },
  { tone: 'safety', icon: Users, sign: { en: 'SUPERVISE', id: 'AWASI' }, title: { en: 'Watch younger players', id: 'Awasi pemain muda' }, detail: { en: 'Children must remain with a responsible adult throughout their visit to the club.', id: 'Anak-anak harus selalu didampingi oleh orang dewasa yang bertanggung jawab selama berada di klub.' } },
  { tone: 'required', icon: ShieldCheck, sign: { en: 'PROTECT', id: 'JAGA' }, title: { en: 'Look after the club', id: 'Jaga fasilitas klub' }, detail: { en: 'Report spills or damage promptly and follow staff directions whenever safety is involved.', id: 'Segera laporkan tumpahan atau kerusakan dan ikuti arahan staf terkait keselamatan.' } },
] as const

export default function RulesPage() {
  const { language } = useLanguage()
  return <div className="rules-page"><SiteHeader active="rules"/><main><section className="rules-hero"><span className="step-label">{language === 'id' ? 'BERMAIN DENGAN BAIK' : 'PLAY WELL'}</span><h1>{language === 'id' ? 'Permainan nyaman dimulai dari kebiasaan baik.' : 'Good games start with good habits.'}</h1><p>{language === 'id' ? 'Delapan panduan sederhana agar setiap sesi aman, bersih, dan menyenangkan.' : 'Eight simple signs to keep every session safe, clean, and enjoyable.'}</p></section><section className="rule-sign-grid">{rules.map(({ tone, icon: Icon, sign, title, detail }, index) => <article className={`rule-sign ${tone}`} key={title.en}><div className="rule-symbol"><Icon size={27}/>{tone === 'prohibited' && <span className="prohibition-slash"/>}</div><div className="rule-copy"><span>{String(index + 1).padStart(2, '0')} · {sign[language]}</span><h2>{title[language]}</h2><p>{detail[language]}</p></div></article>)}</section></main></div>
}
